export interface CompressionOptions {
  enabled?: boolean;
  mode?: 'auto' | 'off' | 'aggressive';
  targetTokens?: number;
}

export interface CompressionTag {
  tag: string;
  count: number;
}

export interface CompressionResult {
  input: string;
  originalInput: string;
  applied: boolean;
  tokensBefore: number;
  tokensAfter: number;
  tokensSaved: number;
  ratio: number;
  method: 'none' | 'llm-gateway' | 'llm-gateway-trim' | 'llm-gateway-signatures';
  strategy: 'none' | 'verbatim_compact' | 'budgeted_high_signal' | 'aggressive_code' | 'signature_map';
  tags: CompressionTag[];
  notes: string[];
}

const DEFAULT_TARGET_TOKENS = parseInt(
  process.env['LLM_GATEWAY_TARGET_TOKENS'] ?? process.env['CTXLEAN_TARGET_TOKENS'] ?? '2400',
  10,
);
const MIN_TOKENS_FOR_COMPRESSION = parseInt(
  process.env['LLM_GATEWAY_MIN_TOKENS'] ?? process.env['CTXLEAN_MIN_TOKENS'] ?? '700',
  10,
);
const MAX_REPEAT_LINE_LENGTH = 600;

type LineKind =
  | 'blank'
  | 'boilerplate'
  | 'comment'
  | 'diff'
  | 'error'
  | 'stacktrace'
  | 'json'
  | 'table'
  | 'import'
  | 'signature'
  | 'path'
  | 'code'
  | 'secret-like'
  | 'metadata'
  | 'text';

type Candidate = {
  text: string;
  strategy: CompressionResult['strategy'];
  method: CompressionResult['method'];
  notes: string[];
  repeatedLines: number;
};

export function estimateTokens(text: string): number {
  if (!text) return 0;
  const cjkChars = text.match(/[\u3040-\u30ff\u3400-\u4dbf\u4e00-\u9fff]/g)?.length ?? 0;
  const words = text.match(/[A-Za-z0-9_]+/g) ?? [];
  const punctuation = text.match(/[^\sA-Za-z0-9_\u3040-\u30ff\u3400-\u4dbf\u4e00-\u9fff]/g)?.length ?? 0;
  const newlinePenalty = Math.ceil((text.match(/\n/g)?.length ?? 0) * 0.25);
  const longWordExtra = words.reduce((sum, word) => sum + Math.max(0, Math.ceil((word.length - 12) / 8)), 0);
  const lexicalEstimate = Math.ceil(words.length * 1.15 + punctuation * 0.45 + cjkChars + newlinePenalty + longWordExtra);
  const characterEstimate = Math.ceil(text.length / 4);
  return Math.max(1, Math.ceil((lexicalEstimate + characterEstimate) / 2));
}

function stripAnsi(input: string): { text: string; changed: boolean } {
  // eslint-disable-next-line no-control-regex -- stripping ANSI escapes requires matching \x1b
  const text = input.replace(/\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])/g, '');
  return { text, changed: text !== input };
}

function normalizeWhitespace(input: string): { text: string; changed: boolean } {
  const text = input
    .replace(/\r\n/g, '\n')
    .replace(/[ \t]+$/gm, '')
    .replace(/\n{4,}/g, '\n\n\n')
    .trim();
  return { text, changed: text !== input };
}

function stripVolatileNoise(line: string): string {
  return line
    .replace(/\b\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:?\d{2})?\b/g, '[TS]')
    .replace(/\b[0-9a-f]{32,64}\b/gi, '[HASH]')
    .replace(/\b((?:pid|request|trace|span|correlation)[_-]?id)[=:]\s*[A-Za-z0-9_.:-]{8,}\b/gi, '$1=[ID]');
}

function normalizeInlineWhitespace(line: string): string {
  return line.trim().replace(/[ \t]{2,}/g, ' ');
}

function isBoilerplateLine(line: string): boolean {
  const lower = line.toLowerCase();
  if (
    lower.startsWith('copyright') ||
    lower.startsWith('licensed under') ||
    lower.startsWith('license:') ||
    lower.startsWith('all rights reserved') ||
    lower.startsWith('generated by') ||
    lower.startsWith('auto-generated')
  ) {
    return true;
  }

  if (line.length >= 4 && /^[=\-_*#./\\ ]+$/.test(line)) return true;
  return false;
}

function classifyLine(line: string): LineKind {
  const trimmed = line.trim();
  if (!trimmed) return 'blank';
  if (isBoilerplateLine(trimmed)) return 'boilerplate';
  if (/^(?:api[_-]?key|token|secret|password|authorization)\s*[:=]\s*\S{8,}/i.test(trimmed)) return 'secret-like';
  if (/^(?:\+{3}|-{3}|@@|\+|-)(?!\d)/.test(trimmed)) return 'diff';
  if (/\b(error|failed|failure|exception|traceback|panic|fatal|denied|unauthorized)\b/i.test(trimmed)) return 'error';
  if (/^\s*(?:at\s+[\w.$/<>-]+|\w+Error:|Traceback \(most recent call last\))/.test(line)) return 'stacktrace';
  if (/^[{[]/.test(trimmed) || /[:,]\s*["\d{[]/.test(trimmed)) return 'json';
  if (/^\|.+\|$/.test(trimmed) || /\S\s{2,}\S\s{2,}\S/.test(trimmed)) return 'table';
  if (/^(?:import|export\s+.*from|from\s+\S+\s+import|require\(|use\s+|#include|package\s+|mod\s+)/.test(trimmed)) return 'import';
  if (/^(?:export\s+)?(?:async\s+)?(?:function|class|interface|type|const|let|var)\s+[A-Za-z_$][\w$]|\b(?:pub\s+)?(?:async\s+)?fn\s+\w+|^(?:def|class)\s+\w+|^func\s+\w+/.test(trimmed)) return 'signature';
  if (/(?:^|[\s"`'])\.?\/?[A-Za-z0-9_.-]+(?:\/[A-Za-z0-9_.-]+)+\.(?:ts|tsx|js|jsx|json|yaml|yml|md|py|go|rs|sql|css|html|sh)\b/.test(trimmed)) return 'path';
  if (/^(?:\/\/|#|\/\*|\*|<!--)/.test(trimmed)) return 'comment';
  if (/[{}();=<>]/.test(trimmed) && /\b(?:const|let|var|return|if|for|while|await|async|fn|def|class|struct|type|interface)\b/.test(trimmed)) return 'code';
  if (/^\[[A-Z0-9_.:-]+\]|\b(?:duration|latency|tokens?|cost|model|provider|route|caller|status)=/i.test(trimmed)) return 'metadata';
  return 'text';
}

function tagLines(input: string): CompressionTag[] {
  const counts = new Map<string, number>();
  for (const line of input.split('\n')) {
    const kind = classifyLine(line);
    if (kind === 'blank') continue;
    counts.set(kind, (counts.get(kind) ?? 0) + 1);
  }
  return [...counts.entries()]
    .sort((a, b) => b[1] - a[1])
    .map(([tag, count]) => ({ tag, count }));
}

function compactRepeatedLines(input: string): { text: string; repeated: number } {
  const output: string[] = [];
  let last = '';
  let repeatCount = 0;
  let repeated = 0;

  const flush = () => {
    if (!last) return;
    output.push(repeatCount > 1 ? `[${repeatCount}x] ${last}` : last);
    if (repeatCount > 1) repeated += repeatCount - 1;
    last = '';
    repeatCount = 0;
  };

  for (const rawLine of input.split('\n')) {
    const line = stripVolatileNoise(normalizeInlineWhitespace(rawLine));
    if (!line) {
      flush();
      if (output[output.length - 1] !== '') output.push('');
      continue;
    }
    if (isBoilerplateLine(line)) continue;

    if (line === last && line.length <= MAX_REPEAT_LINE_LENGTH) {
      repeatCount += 1;
      continue;
    }

    flush();
    last = line;
    repeatCount = 1;
  }
  flush();

  return { text: output.join('\n'), repeated };
}

function dedupeLongLines(input: string): { text: string; removed: number } {
  const seen = new Set<string>();
  let removed = 0;
  const lines = input.split('\n').filter((line) => {
    const normalized = line.trim();
    if (normalized.length < 48) return true;
    if (classifyLine(normalized) === 'error') return true;
    if (seen.has(normalized)) {
      removed++;
      return false;
    }
    seen.add(normalized);
    return true;
  });
  return { text: lines.join('\n'), removed };
}

function isComment(trimmed: string): boolean {
  return (
    /^\/\/(?!\/)/.test(trimmed) ||
    /^#(?![!])/.test(trimmed) ||
    /^\/\*/.test(trimmed) ||
    /^\*/.test(trimmed) ||
    /^<!--/.test(trimmed)
  );
}

function aggressiveCodeCompress(input: string): { text: string; removed: number; collapsedBraces: number } {
  const output: string[] = [];
  let removed = 0;
  let collapsedBraces = 0;
  let inBlockComment = false;
  let braceRun = 0;

  const flushBraces = () => {
    if (braceRun === 0) return;
    if (braceRun <= 3) {
      output.push(...Array.from({ length: braceRun }, () => '}'));
    } else {
      output.push(`}[${braceRun - 1} closing braces collapsed]`);
      collapsedBraces += braceRun - 1;
    }
    braceRun = 0;
  };

  for (const line of input.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed) {
      removed++;
      continue;
    }

    if (inBlockComment) {
      removed++;
      if (trimmed.includes('*/') || trimmed.includes('-->')) inBlockComment = false;
      continue;
    }
    if (trimmed.startsWith('/*') || trimmed.startsWith('<!--')) {
      removed++;
      if (!trimmed.includes('*/') && !trimmed.includes('-->')) inBlockComment = true;
      continue;
    }
    if (isComment(trimmed) && classifyLine(trimmed) !== 'error') {
      removed++;
      continue;
    }

    if (/^(?:}|};|\);|\}\);)$/.test(trimmed)) {
      braceRun++;
      continue;
    }

    flushBraces();
    const indent = line.length - line.trimStart().length;
    output.push(`${' '.repeat(Math.floor(indent / 2))}${trimmed}`);
  }
  flushBraces();

  return { text: output.join('\n'), removed, collapsedBraces };
}

function compactParams(params: string): string {
  return params
    .split(',')
    .map((param) => {
      const p = param.trim();
      if (!p) return '';
      const [name, type] = p.split(':').map((part) => part.trim());
      return type ? `${name}:${type.replace(/\s+/g, '')}` : p.replace(/\s+/g, '');
    })
    .filter(Boolean)
    .join(',');
}

function extractSignatureMap(input: string): string {
  const imports: string[] = [];
  const signatures: string[] = [];
  const seen = new Set<string>();

  for (const line of input.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || isComment(trimmed)) continue;

    if (classifyLine(trimmed) === 'import') {
      const compact = trimmed.replace(/\s+/g, ' ');
      if (!seen.has(compact)) {
        imports.push(compact);
        seen.add(compact);
      }
      continue;
    }

    const jsMatch =
      trimmed.match(/^(?:export\s+)?(?:async\s+)?function\s+([A-Za-z_$][\w$]*)\s*\(([^)]*)\)(?:\s*:\s*([^{]+))?/) ||
      trimmed.match(/^(?:export\s+)?(?:async\s+)?(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=\s*(?:async\s*)?\(([^)]*)\)\s*(?::\s*([^=]+))?/);
    const rustMatch = trimmed.match(/^(?:pub\s+)?(?:async\s+)?fn\s+(\w+)\s*\(([^)]*)\)(?:\s*->\s*([^{]+))?/);
    const pyMatch = trimmed.match(/^def\s+(\w+)\s*\(([^)]*)\)(?:\s*->\s*([^:]+))?/);
    const goMatch = trimmed.match(/^func\s+(\w+)\s*\(([^)]*)\)(?:\s+([^{]+))?/);
    const match = jsMatch ?? rustMatch ?? pyMatch ?? goMatch;

    if (match) {
      const name = match[1] ?? 'anonymous';
      const params = compactParams(match[2] ?? '');
      const returnType = (match[3] ?? '').trim();
      const sig = `fn ${name}(${params})${returnType ? ` -> ${returnType}` : ''}`;
      if (!seen.has(sig)) {
        signatures.push(sig);
        seen.add(sig);
      }
      continue;
    }

    const typeMatch = trimmed.match(/^(export\s+)?(?:class|interface|type|enum|struct|trait)\s+([A-Za-z_$][\w$]*)/);
    if (typeMatch) {
      const sig = trimmed.replace(/\s*[{=].*$/, '').replace(/\s+/g, ' ');
      if (!seen.has(sig)) {
        signatures.push(sig);
        seen.add(sig);
      }
    }
  }

  if (imports.length === 0 && signatures.length === 0) return '';
  return ['[signature map]', ...imports.slice(0, 60), ...signatures.slice(0, 160)].join('\n');
}

function scoreLine(line: string): number {
  const kind = classifyLine(line);
  const weights: Record<LineKind, number> = {
    blank: -2,
    boilerplate: -2,
    comment: -1,
    diff: 8,
    error: 10,
    stacktrace: 9,
    json: 4,
    table: 3,
    import: 5,
    signature: 8,
    path: 6,
    code: 5,
    'secret-like': 7,
    metadata: 4,
    text: 1,
  };
  let score = weights[kind];
  if (/\b(todo|fixme|note|decision|requirement|constraint|token|cost|auth|security|provider|model)\b/i.test(line)) score += 3;
  if (line.length > 500) score -= 2;
  return score;
}

function trimToBudget(input: string, targetTokens: number): { text: string; trimmed: boolean } {
  const targetChars = targetTokens * 4;
  if (input.length <= targetChars) return { text: input, trimmed: false };

  const lines = input.split('\n');
  const headBudget = Math.floor(targetChars * 0.22);
  const tailBudget = Math.floor(targetChars * 0.32);
  const signalBudget = Math.max(0, targetChars - headBudget - tailBudget - 700);

  const highSignal = lines
    .map((line, index) => ({ line, index, score: scoreLine(line) }))
    .filter((item) => item.score >= 5)
    .sort((a, b) => b.score - a.score || a.index - b.index)
    .slice(0, 220)
    .sort((a, b) => a.index - b.index)
    .map((item) => item.line)
    .join('\n')
    .slice(0, signalBudget);

  const text = [
    input.slice(0, headBudget).trim(),
    highSignal ? `[high-signal excerpts]\n${highSignal.trim()}` : '',
    `[tail context]\n${input.slice(-tailBudget).trim()}`,
  ].filter(Boolean).join('\n\n');

  return { text, trimmed: true };
}

function codeSignalRatio(input: string): number {
  const lines = input.split('\n').filter((line) => line.trim());
  if (lines.length === 0) return 0;
  const codeLines = lines.filter((line) => {
    const kind = classifyLine(line);
    return kind === 'code' || kind === 'signature' || kind === 'import' || kind === 'path' || kind === 'comment';
  }).length;
  return codeLines / lines.length;
}

function applySafeguard(original: string, candidate: Candidate, repeatCount: number): Candidate {
  const before = estimateTokens(original);
  const after = estimateTokens(candidate.text);
  if (before === 0) return candidate;
  if (after >= before) {
    return { text: original, strategy: 'none', method: 'none', notes: [...candidate.notes, 'safeguard:inflation-rejected'], repeatedLines: candidate.repeatedLines };
  }

  const ratio = after / before;
  // Repeated operational logs can collapse to a tiny marker while still keeping
  // the representative line, e.g. "[180x] ERROR ...". Do not reject those wins.
  const floor = repeatCount > 20 ? 0.001 : candidate.strategy === 'signature_map' ? 0.08 : 0.15;
  if (ratio < floor) {
    return { text: original, strategy: 'none', method: 'none', notes: [...candidate.notes, `safeguard:ratio-${ratio.toFixed(2)}-rejected`], repeatedLines: candidate.repeatedLines };
  }

  return candidate;
}

function chooseCandidate(input: string, targetTokens: number, mode: CompressionOptions['mode']): Candidate {
  const notes: string[] = [];
  const ansi = stripAnsi(input);
  let text = ansi.text;
  if (ansi.changed) notes.push('ansi-stripped');

  const normalized = normalizeWhitespace(text);
  text = normalized.text;
  if (normalized.changed) notes.push('whitespace-normalized');

  const compact = compactRepeatedLines(text);
  text = compact.text;
  if (compact.repeated > 0) notes.push(`repeated-lines:${compact.repeated}`);

  const deduped = dedupeLongLines(text);
  text = deduped.text;
  if (deduped.removed > 0) notes.push(`deduped-lines:${deduped.removed}`);

  const tokenCount = estimateTokens(text);
  const codeRatio = codeSignalRatio(text);
  const signatureMap = codeRatio >= 0.35 ? extractSignatureMap(text) : '';

  if ((mode === 'aggressive' || tokenCount > targetTokens * 1.4) && signatureMap && estimateTokens(signatureMap) < tokenCount * 0.65) {
    const tail = text.slice(-Math.min(1600, Math.floor(targetTokens * 0.8)));
    return {
      text: `${signatureMap}\n\n[tail context]\n${tail.trim()}`,
      strategy: 'signature_map',
      method: 'llm-gateway-signatures',
      notes: [...notes, 'signature-map'],
      repeatedLines: compact.repeated,
    };
  }

  if (mode === 'aggressive' && codeRatio >= 0.25) {
    const aggressive = aggressiveCodeCompress(text);
    return {
      text: aggressive.text,
      strategy: 'aggressive_code',
      method: 'llm-gateway-trim',
      notes: [...notes, `comments-blank-removed:${aggressive.removed}`, `brace-collapse:${aggressive.collapsedBraces}`],
      repeatedLines: compact.repeated,
    };
  }

  if (tokenCount > Math.max(MIN_TOKENS_FOR_COMPRESSION, targetTokens)) {
    const budgeted = trimToBudget(text, targetTokens);
    return {
      text: budgeted.text,
      strategy: budgeted.trimmed ? 'budgeted_high_signal' : 'verbatim_compact',
      method: 'llm-gateway-trim',
      notes: budgeted.trimmed ? [...notes, `budget:${targetTokens}`] : notes,
      repeatedLines: compact.repeated,
    };
  }

  return { text, strategy: 'verbatim_compact', method: 'llm-gateway', notes, repeatedLines: compact.repeated };
}

export function compressContext(input: string, options: CompressionOptions = {}): CompressionResult {
  const enabled = options.enabled
    ?? (process.env['LLM_GATEWAY_COMPRESSION_ENABLED'] ?? process.env['CTXLEAN_ENABLED']) !== 'false';
  const mode = options.mode ?? 'auto';
  const targetTokens = options.targetTokens ?? DEFAULT_TARGET_TOKENS;
  const originalInput = input;
  const tokensBefore = estimateTokens(originalInput);
  const tags = tagLines(originalInput);

  if (!enabled || mode === 'off') {
    return {
      input,
      originalInput,
      applied: false,
      tokensBefore,
      tokensAfter: tokensBefore,
      tokensSaved: 0,
      ratio: 0,
      method: 'none',
      strategy: 'none',
      tags,
      notes: ['disabled'],
    };
  }

  const chosen = chooseCandidate(input, targetTokens, mode);
  const candidate = applySafeguard(originalInput, chosen, chosen.repeatedLines);
  let text = candidate.text;
  const candidateTokens = estimateTokens(text);
  const candidateSaved = Math.max(0, tokensBefore - candidateTokens);
  const applied = candidate.method !== 'none' && candidateSaved > 0;

  if (applied) {
    const topTags = tags.slice(0, 6).map((tag) => `${tag.tag}:${tag.count}`).join(', ');
    const header = [
      '[LLM Gateway compression]',
      `estimated_tokens: ${tokensBefore} -> ${candidateTokens}`,
      `saved: ${((candidateSaved / Math.max(1, tokensBefore)) * 100).toFixed(1)}%`,
      `strategy: ${candidate.strategy}`,
      topTags ? `tags: ${topTags}` : '',
      `method: ${candidate.notes.join(', ') || 'verbatim_compact'}`,
    ].filter(Boolean).join('\n');
    text = `${header}\n\n${text}`;
  }

  const tokensAfter = estimateTokens(text);
  const tokensSaved = Math.max(0, tokensBefore - tokensAfter);

  return {
    input: text,
    originalInput,
    applied: applied && tokensSaved > 0,
    tokensBefore,
    tokensAfter,
    tokensSaved,
    ratio: tokensBefore > 0 ? tokensSaved / tokensBefore : 0,
    method: applied && tokensSaved > 0 ? candidate.method : 'none',
    strategy: applied && tokensSaved > 0 ? candidate.strategy : 'none',
    tags,
    notes: candidate.notes,
  };
}
